#!/bin/bash
# install-huginn.sh — provision a Mac for Eldr "conduit" mode over SSH.
#
# Generated by ConduitProvisioner (Packages/Eldrctl). Run on the TARGET Mac, e.g.:
#   ssh user@host 'bash -s' -- --owner <hex> --relay <wss> --payload <dir> < install-huginn.sh
# or let `eldrctl install --target user@host …` stage the payload and run it for you.
#
# SECRET-FREE: the LLM token is NEVER an argument here. After this runs, seed it with:
#   printf %s "$ELDR_LLM_TOKEN" | ssh user@host '~/.local/bin/eldr-node --import-token'
#
# HARD REQUIREMENT: the target must have an UNLOCKED user session (auto-login is fine).
# Long-term secrets are WhenUnlockedThisDeviceOnly — the Keychain is unreadable at the
# login window, so a Mac sitting at loginwindow cannot be provisioned or serve.
set -euo pipefail

OWNER=""; RELAY=""; WORKDIR=""; RESPONDER="sybilclaw"; GATEWAY_PORT="18789"
LLM_URL="http://127.0.0.1:1234/v1"; LLM_MODEL="local-model"; PAYLOAD=""
WITH_APP="0"; DRY_RUN="0"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --owner) OWNER="$2"; shift 2;;
    --relay) RELAY="$2"; shift 2;;
    --workdir) WORKDIR="$2"; shift 2;;
    --responder) RESPONDER="$2"; shift 2;;
    --gateway-port) GATEWAY_PORT="$2"; shift 2;;
    --llm-url) LLM_URL="$2"; shift 2;;
    --llm-model) LLM_MODEL="$2"; shift 2;;
    --payload) PAYLOAD="$2"; shift 2;;
    --with-app) WITH_APP="1"; shift;;
    --dry-run) DRY_RUN="1"; shift;;
    *) echo "install-huginn.sh: unknown argument: $1" >&2; exit 2;;
  esac
done

die() { echo "install-huginn.sh: $1" >&2; exit 2; }

# --- Validate (mirrors ConduitProvisioner.validate) -------------------------------
[ -n "$OWNER" ] || die "--owner <64-hex phone identity> is required (the C-3 gate target)."
case "$OWNER" in *[!0-9a-fA-F]*) die "--owner must be 64 hex characters." ;; esac
[ "${#OWNER}" -eq 64 ] || die "--owner must be exactly 64 hex characters."
[ -n "$RELAY" ] || die "--relay <wss://...> is required."
case "$RELAY" in ws://*|wss://*) ;; *) die "--relay must start with ws:// or wss://." ;; esac
[ -n "$WORKDIR" ] || WORKDIR="$HOME"

BIN_DIR="$HOME/.local/bin"
CFG_DIR="$HOME/.config/eldr-acp"
LA_DIR="$HOME/Library/LaunchAgents"
PLIST="$LA_DIR/chat.eldr.node.plist"
LABEL="chat.eldr.node"
UID_NUM="$(id -u)"

mkdir -p "$BIN_DIR" "$CFG_DIR" "$LA_DIR"

# --- Preflight --------------------------------------------------------------------
if [ "$DRY_RUN" = "0" ]; then
  case "$(uname -s)" in Darwin) ;; *) die "this installer targets macOS." ;; esac
  if ! launchctl print "gui/$UID_NUM" >/dev/null 2>&1; then
    die "no unlocked GUI session for uid $UID_NUM. Log in (or enable auto-login) on the target Mac, then re-run — the data-protection Keychain is unreadable at the login window."
  fi
fi

# --- Locate the staged payload (Huginn.app + eldr-node) ---------------------------
APP_SRC=""; NODE_SRC=""; ACP_SRC=""
if [ -n "$PAYLOAD" ]; then
  [ -d "$PAYLOAD/Huginn.app" ] && APP_SRC="$PAYLOAD/Huginn.app"
  [ -f "$PAYLOAD/eldr-node" ] && NODE_SRC="$PAYLOAD/eldr-node"
  [ -f "$PAYLOAD/eldr-acp" ] && ACP_SRC="$PAYLOAD/eldr-acp"
fi
if [ -z "$NODE_SRC" ] && [ -f "/Applications/Huginn.app/Contents/Resources/eldr-node" ]; then
  NODE_SRC="/Applications/Huginn.app/Contents/Resources/eldr-node"
fi

# --- Install the full app (optional) ----------------------------------------------
if [ "$WITH_APP" = "1" ] && [ -n "$APP_SRC" ]; then
  echo "==> Installing $APP_SRC -> /Applications/Huginn.app"
  if [ "$DRY_RUN" = "0" ]; then
    ditto "$APP_SRC" "/Applications/Huginn.app"
    xattr -dr com.apple.quarantine "/Applications/Huginn.app" 2>/dev/null || true
    codesign --verify --strict "/Applications/Huginn.app" || die "Huginn.app failed codesign --verify."
    spctl -a -t exec "/Applications/Huginn.app" 2>/dev/null || echo "  note: Gatekeeper assessment did not pass (unsigned dev build?)."
  fi
  [ -z "$NODE_SRC" ] && [ -f "/Applications/Huginn.app/Contents/Resources/eldr-node" ] && NODE_SRC="/Applications/Huginn.app/Contents/Resources/eldr-node"
fi

# --- Install the node binary ------------------------------------------------------
[ -n "$NODE_SRC" ] || die "eldr-node binary not found. Pass --payload <dir containing eldr-node> or install Huginn.app."
echo "==> Installing eldr-node -> $BIN_DIR/eldr-node"
if [ "$DRY_RUN" = "0" ]; then
  install -m 0755 "$NODE_SRC" "$BIN_DIR/eldr-node"
  [ -n "$ACP_SRC" ] && install -m 0755 "$ACP_SRC" "$BIN_DIR/eldr-acp"
fi

# --- Write conduit config (NO token here — C-8) -----------------------------------
umask 077
cat > "$CFG_DIR/env" <<ENVEOF
# Written by install-huginn.sh — do not edit by hand. No token here (C-8: it lives in
# the Keychain, seeded via 'eldr-node --import-token').
export ELDR_LLM_URL='$LLM_URL'
export ELDR_LLM_MODEL='$LLM_MODEL'
export PQRC_RELAY_URL='$RELAY'
ENVEOF
printf '%s\n' "$OWNER" > "$CFG_DIR/owner"
printf '%s\n' "$WORKDIR" > "$CFG_DIR/workdir"
printf '%s\n' "$RESPONDER" > "$CFG_DIR/responder"

# --- Write + load the LaunchAgent (Aqua session => Keychain unlocked) -------------
cat > "$PLIST" <<PLISTEOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$BIN_DIR/eldr-node</string>
    <string>--owner</string><string>$OWNER</string>
    <string>--relay</string><string>$RELAY</string>
    <string>--workdir</string><string>$WORKDIR</string>
    <string>--responder</string><string>$RESPONDER</string>
    <string>--gateway-port</string><string>$GATEWAY_PORT</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>LimitLoadToSessionType</key><string>Aqua</string>
  <key>StandardOutPath</key><string>$CFG_DIR/eldr-node.log</string>
  <key>StandardErrorPath</key><string>$CFG_DIR/eldr-node.log</string>
</dict>
</plist>
PLISTEOF

if [ "$DRY_RUN" = "0" ]; then
  launchctl bootout "gui/$UID_NUM" "$PLIST" 2>/dev/null || true
  launchctl bootstrap "gui/$UID_NUM" "$PLIST"
  echo "==> LaunchAgent $LABEL loaded (RunAtLoad, KeepAlive)."
fi

cat <<'HINT'

Next: seed the LLM token. Pipe it over SSH so it never touches disk, argv, or history:

    printf %s "$ELDR_LLM_TOKEN" | ssh <user@host> '~/.local/bin/eldr-node --import-token'

HINT

if [ "$DRY_RUN" = "0" ]; then
  echo "Pairing link — scan or paste into EldrChat (new conversation):"
  "$BIN_DIR/eldr-node" --print-pairing-link --relay "$RELAY" || true
fi