#!/bin/sh
# setup-signing.sh — write the gitignored Signing.local.xcconfig once per clone.
#
# After this runs, the Xcode GUI, `xcodebuild`, and the test commands in CLAUDE.md
# all sign with your team and NOTHING about you is tracked by git.
#
#   ./scripts/setup-signing.sh              # auto-detect from your keychain
#   ./scripts/setup-signing.sh ABCDE12345   # or name the team explicitly
#
# Detection deliberately prefers a team you can ACTUALLY sign with today. Having a
# certificate is not sufficient: the team's Apple ID must also be signed in under
# Xcode ▸ Settings ▸ Accounts, or the build dies with
#
#   error: No Account for Team "…". Add a new account in Accounts settings.
#   error: No signing certificate "Mac Development" found: … team ID "…"
#
# The second line is a consequence of the first, so chasing the certificate is a
# dead end — and this machine has certs for two teams, only one of which is signed
# in. Picking the wrong one is what wasted a debugging session on 2026-08-06.

set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
out="$repo_root/Signing.local.xcconfig"

team=${1:-}

profile_dir="$HOME/Library/Developer/Xcode/UserData/Provisioning Profiles"

# Team ids Xcode holds provisioning profiles for, most profiles first.
detect_from_profiles() {
	[ -d "$profile_dir" ] || return 0
	for p in "$profile_dir"/*.provisionprofile "$profile_dir"/*.mobileprovision; do
		[ -e "$p" ] || continue
		security cms -D -i "$p" 2>/dev/null \
			| plutil -extract TeamIdentifier.0 raw - 2>/dev/null
	done | sort | uniq -c | sort -rn | awk 'NR==1{print $2}'
}

if [ -z "$team" ]; then
	# PROFILES FIRST — not keychain certificates.
	#
	# A certificate proves you hold a key; a provisioning profile proves Xcode has
	# an ACCOUNT for that team and can mint profiles for it. Those come apart, and
	# on at least one machine here they point at DIFFERENT teams: every "Apple
	# Development" cert in the keychain belongs to one team, while every
	# provisioning profile — and the only team that actually builds — belongs to
	# another. A cert-frequency heuristic confidently picks the team that cannot
	# build. Profiles are the ground truth.
	team=$(detect_from_profiles)
fi

if [ -z "$team" ]; then
	# No profiles yet (Xcode has never signed anything here). Fall back to certs
	# and say plainly that this is the weaker signal.
	team=$(security find-identity -v -p codesigning 2>/dev/null \
	       | sed -n 's/.*"Apple Development:.*(\([A-Z0-9]\{10\}\))".*/\1/p' \
	       | sort | uniq -c | sort -rn | awk 'NR==1{print $2}')
	[ -n "$team" ] && echo "setup-signing: no provisioning profiles found; guessing $team from your keychain." >&2
fi

if [ -z "$team" ]; then
	echo "setup-signing: could not find an 'Apple Development' identity in your keychain." >&2
	echo "" >&2
	echo "What you have:" >&2
	security find-identity -v -p codesigning >&2 || true
	echo "" >&2
	echo "Open Xcode ▸ Settings ▸ Accounts, sign in, let it create a" >&2
	echo "development certificate, then re-run this. Or pass the id yourself:" >&2
	echo "  ./scripts/setup-signing.sh ABCDE12345" >&2
	exit 1
fi

cat > "$out" <<EOF
// GENERATED by scripts/setup-signing.sh — gitignored, never commit this.
// Your Apple Team ID. Consumed by Signing.xcconfig, which both projects use.
ELDR_DEV_TEAM = $team
EOF

echo "setup-signing: wrote $out"
echo "setup-signing: ELDR_DEV_TEAM = $team"
echo ""

# Loud check: does Xcode hold profiles for this team? That, not a certificate,
# is what predicts whether the build survives.
if [ "$(detect_from_profiles)" = "$team" ] || \
   { [ -d "$profile_dir" ] && grep -rlq "$team" "$profile_dir" 2>/dev/null; }; then
	echo "setup-signing: Xcode holds provisioning profiles for $team. Good."
else
	echo "setup-signing: WARNING — no provisioning profile for $team." >&2
	echo "setup-signing: expect 'No Account for Team \"$team\"' plus a misleading" >&2
	echo "setup-signing: 'No signing certificate found' line. Sign that team's" >&2
	echo "setup-signing: Apple ID in under Xcode ▸ Settings ▸ Accounts." >&2
fi

if ! git -C "$repo_root" check-ignore -q "$out"; then
	echo "setup-signing: ERROR — $out is NOT gitignored. Fix .gitignore before building." >&2
	exit 1
fi
echo "setup-signing: confirmed gitignored."
